name: flutter_customerfeedback_api
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  cupertino_icons: ^1.0.8
  onesignal_flutter: ^5.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/CapeGlobe.jpg
    - lib/images/softtouch.png
    - lib/images/brain.jpg
    - lib/images/soft1.jpg
